### ISSUE TITLE
API com problema

### ISSUE THREAD

**Issue by thomfilg** [wilsonfreitas/cvm-funds-php#1]
Olá, o script não está fazendo login na CVM, você sabe o que pode ser?

tentei acessar: cvmwebmethods.php?methodname=solicAutorizDownloadArqComptc&iCdTpDoc=209&strDtComptcDoc=2015-07-09

Apareceu a mensagem: PermissÃ£o negada. Por favor, efetue o login antes de acessar essa funcionalidade. 

PS: fiz cadastro na CVM e corrigi urls da API que mudaram, mas é como se não registrasse o soap header para as chamadas subsequentes na API, ou como se o soap header não fosse enviado. 

só para ilustrar, um trecho de código adaptado (pois colar vários arquivos aqui ficaria difícil):

``` php
$client = new SoapClient("http://sistemas.cvm.gov.br/webservices/Sistemas/SCW/CDocs/WsDownloadInfs.asmx?WSDL",array(
      "trace"           => true, 
      "exceptions"  => true, 
      "cache_wsdl" => false
));
$client->Login(array("iNrSist" => 2017, "strSenha" => '******'));     

//seta o header sessaoIdHeader
$response = $client->__getLastResponse();
$xml = simplexml_load_string($response);
$xml->registerXPathNamespace('cvm', 'http://sistemas.cvm.gov.br/webservices/');
$item = $xml->xpath('//soap:Header');
$token = $item[0]->sessaoIdHeader;
$header = new SoapHeader('http://sistemas.cvm.gov.br/webservices/', 'sessaoIdHeader',  array('Guid' => $token->Guid, 'IdSessao' => $token->IdSessao));
$client->__setSoapHeaders($header);

//solicita o download de documentos
try{
    $response = $client->solicAutorizDownloadCadastro(array(
         'strDtRefer' => '2015-12-03'
    ));
    print_r($response);
}catch(Exception $e){
    die($e->getMessage());
}
```

**Comment by wilsonfreitas** [comment]
Dê uma olhada no script `cvmwebmethods.php`, mas antes de executar é importante configurar o usuário e senha no script `lib.cvm.php` (bem no começo).

``` php
$cvm['nr-sist'] = 0000;
$cvm['senha'] = "xxxxx";
```

Segue um exemplo de como eu uso o `cvmwebmethods.php`

```
cvmwebmethods.php?methodname=solicAutorizDownloadArqComptc&iCdTpDoc=209&strDtComptcDoc=2014-07-09
```

Venho usando diariamente sem problemas. Dê uma olhada na sequencia que começa nos webmethods, isso pode te ajudar a entender como eu uso a API. Essa API da CVM é um tanto hostil.

**Comment by thomfilg** [comment]
Olá Wilson,
Obrigado pela resposta! 

Mas o problema do trecho de código que postei era outro: Depois de averiguar seu código vi que o namespace que estava usando estava errado, o correto era: 

``` PHP
$xml->registerXPathNamespace('cvm', 'http://cvm.gov.br/webservices/');
```

Foi só mudar esta linha que funcionou! :smile: 

Mas realmente.. a API da CVM tem que usar com cuidado! Só podem ser feitas 10 requisições por dia! Em fase de desenvolvimento isto é muito pouco e atrasa bastante a produção.

**Comment by joaoderoldo** [comment]
Wilson boa tarde, estou com uma duvida, como eu consigo os seguintes dados

$cvm['nr-sist'] = 0000;
$cvm['senha'] = "xxxxx";

Aonde eu faço o cadastro para conseguir isso ?
